Lesson21
cedrikns/javaEEDevEdu pull request #10
Opened 2020-12-18 22:30 UTC by cedrikns

В классе FileStorage реализовано сохранение данных в файл в формате json.

2020-12-20 15:31 UTC, efremov-itcenter requested changes

2020-12-20 15:31 UTC, efremov-itcenter commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +                                return pet.getId();
Здесь будет NPE, если случится исключение в 37 строке. В результате, понять, что именно случилось, будет непросто. Лучше в 39 строке не просто печатать стектрейс, но повторно кидить исключение, обернув его в RuntimeException: `throw new RuntimeException(e)`

2020-12-20 15:31 UTC, efremov-itcenter commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +    private void getAllIds(){
А почему бы не вернуть айдишники из метода, а не присваивать их полю класса?

2020-12-20 15:31 UTC, efremov-itcenter commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +        return true;
Почему всегда возвращается `true`? Выглядит разумно вернуть `false` в случае возникновения исключения (после строки 55)

2020-12-20 15:31 UTC, efremov-itcenter commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +            e.printStackTrace();
Выглядит опасно. Клиентский код никогда не узнает, что здесь произошла беда :(
Лучше бросить исключение после логирования ошибки: `throw new RuntimeException(e)`

2020-12-20 15:31 UTC, efremov-itcenter commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +                                p = objectMapper.readValue(s, Pet.class);
Переменная `p` здесь не особо нужна.
Лучше написать без затей `return objectMapper.readValue(s, Pet.class);`

2020-12-20 15:31 UTC, efremov-itcenter commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +                                e.printStackTrace();
А здесь придется выбросить исключение (все по той же схеме, обернув его в `RuntimeException`)

2020-12-20 15:31 UTC, efremov-itcenter commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +                return p;
Вот это все повторяется в нескольких методах - можно либо выделить в отдельный метод, либо присвоить переменной типа Consumer / Function

2020-12-20 15:31 UTC, efremov-itcenter commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/PetsCardFile.java
> +    public PetsCardFile(String fileName){
Напрашивается передавать `storage` в конструкторе, причем лучше выделить интерфейс, обозвать его, например, `PetStorage`, и `FileStorage` унаследовать от него. Тогда при старте приложения мы сможем выбирать, как хранить питомцев - можно будет создать дополнительные реализации `PetStorage` для хранения в памяти, базе данных, замокать для тестирования и т.д.

2020-12-30 10:57 UTC, cedrikns commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +    private void getAllIds(){
Переделала

2020-12-30 10:58 UTC, cedrikns commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +                                return pet.getId();
Добавила

2020-12-30 10:58 UTC, cedrikns commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +            e.printStackTrace();
Добавила

2020-12-30 11:00 UTC, cedrikns commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +        return true;
Добавила после печати стектрейса проброс исключения.

2020-12-30 11:00 UTC, cedrikns commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +                                p = objectMapper.readValue(s, Pet.class);
Удалила переменную p

2020-12-30 11:01 UTC, cedrikns commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +                                e.printStackTrace();
Добавила

2020-12-30 11:01 UTC, cedrikns commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/FileStorage.java
> +                return p;
Вынесла в переменную deserializePet

2020-12-30 11:09 UTC, cedrikns commented on JavaEEDeveloper/src/main/java/ru/tsedrik/lesson21/PetsCardFile.java
> +    public PetsCardFile(String fileName){
Добавила. 
Сразу хотела использовать Storage c generic-типами, но появилась проблема, что у дженериков нельзя получать .class. А для десериализации это нужно было. Поэтому убрала интерфейс.

2021-05-01 21:24 UTC, merged